### ISSUE TITLE
Always returning 'http://dpaste.com/api/v2/'

### ISSUE THREAD

**Issue by stolksdorf** [H25/dpaste-sublime#2]
There's been a slight change to the dpaste API. I believe it's affecting your plugin.

**Comment by aliteralmind** [comment]
Confirmed. Seemed to start sometime today. The returned url is always the one in this issue's subject line. I'm Using build 3065, on Win 8.1, 64bit

**Comment by hieuh25** [comment]
Thanks for reporting, the problem has been fixed in master, please update the plugin.

**Comment by aliteralmind** [comment]
Thank you. I will update it manually. I'm curious how long it takes for updates like this to make their way to Package Control?

**Comment by aliteralmind** [comment]
Hup! Seems to already be there. It was automatically updated.  :)

**Comment by stolksdorf** [comment]
@H25 Fantastic job and amazing turn around time. I felt mostly responsible to breaking your plugin since I requested the API change to dpaste. Sorry about that!

**Comment by hieuh25** [comment]
@aliteralmind I have no idea to be honest, I just know that it would happen automatically, my guess is every hour.

@stolksdorf no problem, thanks for letting me know that the plugin was broken. I don't really use it daily :D
